<?php

namespace Modules\Setting\Entities\V1;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $guarded = [];
//     protected $fillable = [
//         'id',
//         'initial',
//         'name',
//         'description',
//         'icon',
//         'logo',
//         'login_image',
//         'news',
//         'news_desc',
//         'news_background',
//         'welcome',
//         'welcome_desc',
//         'welcome_image',
//         'find_us_image',
//         'testimony_category_id',
//         'page_category_id',
//         'event_category_id',
//         'testimony_background',
//         'phone',
//         'address_short',
//         'address_long',
//         'working_hour',
//         'email',
//         'facebook',
//         'twitter',
//         'google',
//         'instagram',
//         'award',
//         'copyright',
//         'about_us',
//         'about_us_desc_long',
//         'about_us_who',
//         'about_us_what',
//         'about_us_include',
//         'about_us_background',
//         'team',
//         'team_desc',
//         'contact',
//         'contact_desc',
//         'contact_desc_long',
//         'contact_background',
//         'maps_key',
//         'latitude',
//         'longitude',
//         'api_key',
//         'goal',
//         'goal_desc',
//         'gallery',
//         'gallery_desc',
//         'admission',
//         'admission_desc',
//         'event',
//         'event_desc',
//         'testimony',
//         'testimony_desc',
// ];
}
